<?php
/**
 * Plugin Name: MFR Keyword Limiter
 * Plugin URI: https://github.com/mikezielonkadotcom/mfr-keyword-limiter
 * Description: Smart focus keyword distribution for Media File Renamer AI alt/title prompts, keeping keywords on priority images while avoiding keyword stuffing.
 * Version: 1.0.4
 * Requires at least: 6.0
 * Requires PHP: 7.4
 * Update URI: https://updatemachine.com/mfr-keyword-limiter/update.json
 * Author: Mike Zielonka Ventures
 * Author URI: https://mikezielonka.com
 * License: GPL-2.0-or-later
 * Text Domain: mfr-keyword-limiter
 *
 * @package MFR_Keyword_Limiter
 */

defined( 'ABSPATH' ) || exit;

define( 'MFR_KEYWORD_LIMITER_VERSION', '1.0.4' );
define( 'MFR_KEYWORD_LIMITER_FILE', __FILE__ );
define( 'MFR_KEYWORD_LIMITER_PATH', plugin_dir_path( __FILE__ ) );

require_once MFR_KEYWORD_LIMITER_PATH . 'includes/um-updater.php';
require_once MFR_KEYWORD_LIMITER_PATH . 'includes/class-mfr-feature-telemetry.php';

if ( function_exists( 'UM\\PluginUpdater\\register' ) ) {
	$GLOBALS['mfr_keyword_limiter_updater'] = \UM\PluginUpdater\register(
		array(
			'file'       => MFR_KEYWORD_LIMITER_FILE,
			'slug'       => 'mfr-keyword-limiter',
			'update_url' => 'https://updatemachine.com/mfr-keyword-limiter/update.json',
			'server'     => 'https://updatemachine.com',
			'telemetry_consent_mode' => 'opt_in',
			'telemetry_data_description' => __( 'When enabled, sends only integration availability and detected SEO provider plus standard update diagnostics. No keywords, prompts, media data, content, user data, or credentials.', 'mfr-keyword-limiter' ),
			'feature_telemetry' => MFR_Feature_Telemetry::config(),
		)
	);
}

/**
 * Register the updater privacy field on Settings > General.
 */
function mfr_keyword_limiter_register_updater_privacy_field(): void {
	add_settings_section(
		'mfr_keyword_limiter_update_privacy',
		__( 'MFR Keyword Limiter Privacy', 'mfr-keyword-limiter' ),
		'__return_false',
		'general'
	);

	add_settings_field(
		'mfr_keyword_limiter_um_telemetry_opt_out',
		__( 'Update Telemetry', 'mfr-keyword-limiter' ),
		'mfr_keyword_limiter_render_updater_privacy_field',
		'general',
		'mfr_keyword_limiter_update_privacy'
	);
}
add_action( 'admin_init', 'mfr_keyword_limiter_register_updater_privacy_field' );

/**
 * Render the Update Machine telemetry opt-out field.
 */
function mfr_keyword_limiter_render_updater_privacy_field(): void {
	$updater = $GLOBALS['mfr_keyword_limiter_updater'] ?? null;

	if ( $updater && method_exists( $updater, 'telemetry_preference' ) ) {
		$updater->telemetry_preference()->render_control();
		return;
	}

	echo '<p class="description">' . esc_html__( 'Update telemetry controls are unavailable until the bundled updater finishes loading.', 'mfr-keyword-limiter' ) . '</p>';
}

add_filter( 'mfrh_ai_prompt', 'mfr_keyword_limiter_limit_keyword_in_prompt', 10, 3 );

/**
 * Limit focus keyword usage in Media File Renamer AI alt/title prompts.
 *
 * Featured images and WPRM recipe images keep the original prompt so they can
 * receive the target keyword. Once two non-priority sibling images already use
 * the target keyword in alt text, additional image prompts are adjusted to ask
 * for natural descriptive metadata without forcing the keyword.
 *
 * @param string $prompt        AI prompt generated by Media File Renamer.
 * @param string $metadata_type Metadata type being generated, such as alt/title.
 * @param object $entry         Attachment post object supplied by Media File Renamer.
 * @return string Filtered AI prompt.
 */
function mfr_keyword_limiter_limit_keyword_in_prompt( $prompt, $metadata_type, $entry ) {
	if ( ! in_array( $metadata_type, array( 'alt', 'title' ), true ) ) {
		return $prompt;
	}

	if ( empty( $entry ) || empty( $entry->post_parent ) || empty( $entry->ID ) ) {
		return $prompt;
	}

	$parent_id  = (int) $entry->post_parent;
	$current_id = (int) $entry->ID;

	$featured_id = (int) get_post_thumbnail_id( $parent_id );
	if ( $current_id === $featured_id && $featured_id > 0 ) {
		return $prompt;
	}

	$wprm_recipes = get_posts(
		array(
			'post_type'      => 'wprm_recipe',
			'post_parent'    => $parent_id,
			'posts_per_page' => 5,
			'fields'         => 'ids',
			'post_status'    => 'any',
		)
	);

	foreach ( $wprm_recipes as $recipe_id ) {
		$recipe_image = get_post_meta( $recipe_id, 'wprm_recipe_image', true );
		if ( (int) $recipe_image === $current_id ) {
			return $prompt;
		}

		$recipe_thumb = (int) get_post_thumbnail_id( $recipe_id );
		if ( $recipe_thumb === $current_id && $recipe_thumb > 0 ) {
			return $prompt;
		}
	}

	$keyword = get_post_meta( $parent_id, '_yoast_wpseo_focuskw', true );
	if ( empty( $keyword ) ) {
		$keyword = get_post_meta( $parent_id, 'rank_math_focus_keyword', true );
	}
	if ( empty( $keyword ) ) {
		$keyword = get_post_meta( $parent_id, '_seopress_analysis_target_kw', true );
	}
	if ( empty( $keyword ) || ! is_string( $keyword ) ) {
		return $prompt;
	}

	$keyword_primary = trim( explode( ',', $keyword )[0] );
	if ( '' === $keyword_primary ) {
		return $prompt;
	}

	$keyword_lower = function_exists( 'mb_strtolower' ) ? mb_strtolower( $keyword_primary ) : strtolower( $keyword_primary );

	$attachments = get_posts(
		array(
			'post_type'      => 'attachment',
			'post_parent'    => $parent_id,
			'post_mime_type' => 'image',
			'posts_per_page' => -1,
			'fields'         => 'ids',
			'post__not_in'   => array( $current_id ),
		)
	);

	$priority_ids = array();
	if ( $featured_id > 0 ) {
		$priority_ids[] = $featured_id;
	}

	foreach ( $wprm_recipes as $recipe_id ) {
		$recipe_image = (int) get_post_meta( $recipe_id, 'wprm_recipe_image', true );
		if ( $recipe_image > 0 ) {
			$priority_ids[] = $recipe_image;
		}

		$recipe_thumb = (int) get_post_thumbnail_id( $recipe_id );
		if ( $recipe_thumb > 0 ) {
			$priority_ids[] = $recipe_thumb;
		}
	}

	$priority_ids      = array_unique( $priority_ids );
	$keyword_count     = 0;
	$max_with_keyword  = 2;

	foreach ( $attachments as $attachment_id ) {
		$attachment_id = (int) $attachment_id;
		if ( in_array( $attachment_id, $priority_ids, true ) ) {
			continue;
		}

		$alt       = get_post_meta( $attachment_id, '_wp_attachment_image_alt', true );
		$alt_lower = is_string( $alt ) ? ( function_exists( 'mb_strtolower' ) ? mb_strtolower( $alt ) : strtolower( $alt ) ) : '';

		if ( '' !== $alt_lower && false !== strpos( $alt_lower, $keyword_lower ) ) {
			$keyword_count++;
		}
	}

	if ( $keyword_count >= $max_with_keyword ) {
		$filtered_prompt = preg_replace(
			'/\* SEO keywords related to the media:.*?\n/',
			'',
			$prompt
		);

		if ( is_string( $filtered_prompt ) ) {
			$prompt = $filtered_prompt;
		}

		$prompt .= "\n\nIMPORTANT: Other images in this post already use the target keyword. "
			. 'For this image, write a natural, descriptive ' . $metadata_type
			. ' that accurately describes what is shown WITHOUT forcing any specific keyword. '
			. 'Focus on being helpful and descriptive for accessibility.';
	}

	return $prompt;
}
